wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"

urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.get_page, name="entries"),
    path("search", views.get_page, name="search"),
    path("create", views.new_page, name="create"),
    path("edit/<str:title>", views.edit_entry, name="edit"),
    path("random", views.random_page, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import markdown2
import random

from . import util

class SearchForm(forms.Form):
    key = forms.CharField(label="Search Encyclopedia")

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"row":5, "cols":10}))

class EditForm(forms.Form):
    title = forms.CharField(label="Title")
    content = forms.CharField(widget=forms.Textarea(attrs={"row":5, "cols":10}))
     
def title_existed(title):
    return title.upper() in map(lambda x: x.upper(), util.list_entries())

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(), 
        "search_form": SearchForm(),
        "heading": "All Pages"
    })

def get_page(request, title = None):
    search_form = SearchForm()
    #When using search form
    if request.method == "POST":
        search_form = SearchForm(request.POST)
        if search_form.is_valid():
            #get search key term
            title = search_form.cleaned_data["key"]
            #if exact title not found then output a search results page
            #otherwise render the page if search term matches correct title
            if not title_existed(title):
                search_results = list(filter(lambda x: title.upper() in x.upper(), util.list_entries()))
                return render(request, "encyclopedia/index.html", {
                        "entries": search_results, 
                        "search_form": search_form,
                        "heading": f"Search Results: {title}"
    })

    #if input url is an invalid title
    if not title_existed(title):
        return render(request, "encyclopedia/not_found.html", {
            "title": title, "search_form": search_form
        })
    #when using direct url or searched title is available
    content = markdown2.markdown(util.get_entry(title))
    return render(request, "encyclopedia/entry.html", {
        "title": title, "content": content, "search_form": search_form
    })


def new_page(request):
    error_msg = None
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            if not title_existed(title):
                util.save_entry(title, form.cleaned_data["content"])
                return get_page(request, title)
            #if entry already existed
            else:
                error_msg = "This entry is already in the encyclopedia"
    else:
        form = NewPageForm()
    return render(request, "encyclopedia/create.html", {
            "title": "New entry", "new_page_form": form, "error_msg": error_msg, "search_form": SearchForm()
    })
    
def edit_entry(request, title):
    
    if request.method == "POST":
        form = EditForm(request.POST)
        if form.is_valid():
            new_content = form.cleaned_data["content"]
            util.save_entry(title, new_content)
            return get_page(request, title)
    #initialize entry data
    form = EditForm()
    form.fields["title"].initial = title
    form.fields["content"].initial = util.get_entry(title)
    
    return render(request, "encyclopedia/edit.html", {
        "title": title, "form": form, "search_form": SearchForm()
    })

def random_page(request):
    return get_page(request, title = random.choice(util.list_entries()))

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    <h1>New page</h1>

    <form action="{% url 'wiki:create' %}" method="POST">
        {% csrf_token %}
        {% if error_msg is not None %}
            <p class="isa_error" style="color: #D8000C; background-color: #FFD2D2;">{{ error_msg }}</p>
        {% endif %}
        {{ new_page_form }}
        <input type="submit" value="Create">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit entry
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <form action="{% url 'wiki:edit' title=title %}" method="POST">
        {% csrf_token %}
        {{form}}
        <input type="submit" value="Save">
        <input type="button" value="Cancel" onclick="history.back()">
    </form>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    {{content|safe}}
    <a href="{% url 'wiki:edit' title=title %}">Edit</a>
{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ heading }}</h1>
    
    <ul>
        {% for entry in entries %}
            <a href="{% url 'wiki:entries' title=entry %}">{{ entry }}</aa>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="POST">
                    {% csrf_token %}
                    {{ search_form }}
                    <input type="submit" name="search" id="search">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Not available
{% endblock %}

{% block body %}
    <h1>Not found</h1>
    <div> There is no information yet on "{{ title }}"</div>
{% endblock %}